src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $eventDateTime = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_email = null;

    #[ORM\Column]
    private ?string $contact_phone_number = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    private ?string $event_URL = null;

    #[ORM\Column(length: 50)]
    private ?string $eventType = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEventDateTime(): ?\DateTimeInterface
    {
        return $this->eventDateTime;
    }

    public function setEventDateTime(\DateTimeInterface $eventDateTime): static
    {
        $this->eventDateTime = $eventDateTime;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhoneNumber(): ?string
    {
        return $this->contact_phone_number;
    }

    public function setContactPhoneNumber(string $contact_phone_number): static
    {
        $this->contact_phone_number = $contact_phone_number;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getEventURL(): ?string
    {
        return $this->event_URL;
    }

    public function setEventURL(string $event_URL): static
    {
        $this->event_URL = $event_URL;

        return $this;
    }

    public function getEventType(): ?string
    {
        return $this->eventType;
    }

    public function setEventType(string $eventType): static
    {
        $this->eventType = $eventType;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', type: null, options: [
                "label" => "Enter the Event Name",
                "attr" => [ "placeholder" => "Event Name", "class" => "form-control"]
                ] )
            ->add('eventDateTime', null, [
                'widget' => 'single_text',
                'label' => 'Event Date and Time',
                'attr' => ['class' => 'form-control datetimepicker-input']
            ])
            ->add('description', type:null, options: [
                "label" => "Enter the Event Description",
                 "attr" => [ "placeholder" => "Event Description", "class" => "form-control"]
                ])
            ->add('image', type: null, options: [
                "label" => "Image URL",
                "attr" => [ "placeholder" => "Image URL", "class" => "form-control"]
                ])
            ->add('capacity', type:null, options:[
                "label" => "Enter the Event Capacity",
                "attr" => [ "placeholder" => "Event Capacity", "class" => "form-control"]
                ])
            ->add('contact_email', type:null, options: [
                "label" => "Enter the Event Contact Email",
                "attr" => [ "placeholder" => "Event Contact Email", "class" => "form-control"]
                ])
            ->add('contact_phone_number', type:null, options:[
                "label" => "Enter the Event Contact Phone Number",
                "attr" => [ "placeholder" => "Event Contact Phone Number", "class" => "form-control"]
                ])
            ->add('adress', type:null, options: [
                "label" => "Where is the Event located?",
                "attr" => [ "placeholder" => "Enter the adress", "class" => "form-control"]
                ])
            ->add('event_URL', type:null, options:[
                "label" => "Enter the Event URL",
                "attr" => [ "placeholder" => "Event URL", "class" => "form-control"]
                ])
            ->add('eventType', ChoiceType::class, [
                "choices" => [
                    "Music" => "Music",
                    "Sports" => "Sports",
                    "Movie" => "Movie",
                    "Theater" => "Theater",
                    "Food" => "Food",
                    "Art" => "Art",
                    "Other" => "Other"
                ],
                "label" => "Select the Event Type",
                'placeholder' => 'Select the event type',
                "attr" => [ "class" => "form-control"]
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/events')]
final class EventsController extends AbstractController
{
    #[Route(name: 'app_events_index', methods: ['GET'])]
    public function index(EventsRepository $eventsRepository, Request $request): Response
    {
        $eventType = $request->query->get('type');
        $events = $eventType ? $eventsRepository->findBy(['eventType' => $eventType]) : $eventsRepository->findAll();
        return $this->render('events/index.html.twig', [
            'events' => $events,
            'eventType' => $eventType,
        ]);
    }

    #[Route('/new', name: 'app_events_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_show', methods: ['GET'])]
    public function show(Events $event): Response
    {
        return $this->render('events/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_events_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_delete', methods: ['POST'])]
    public function delete(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/events/_delete_form.html.twig
<form method="post" action="{{ path('app_events_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <br>
    <button class="btn btn-danger fs-3">Delete</button>
</form>

templates/events/_form.html.twig
<div class="formclass">
{{ form_start(form, {'attr': {'class': 'btn btn-dark'}}) }}
    {{ form_widget(form) }}
    <br>
    <button class=" cardColor btn btn-light">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
</div>

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Events{% endblock %}

{% block body %}
    <h1 class="text-center">Edit Events</h1>
   
    {{ include('events/_form.html.twig', {'button_label': 'Update'}) }}

   

   <div class="text-center own">
    <br>
    <a class="btn btn-success fs-3" href="{{ path('app_events_index') }}">Back to events</a>

    {{ include('events/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events index{% endblock %}

{% block body %}
    <h1 class="text-center">Events in Vienna</h1>
    <div class="text-center mb-4">
        <form method="get" action="{{ path('app_events_index') }}">
            <select name="type" class="form-select" onchange="this.form.submit()">
                <option value="">All Types</option>
                <option value="Music" {% if eventType == 'Music' %}selected{% endif %}>Music</option>
                <option value="Sports" {% if eventType == 'Sports' %}selected{% endif %}>Sports</option>
                <option value="Movie" {% if eventType == 'Movie' %}selected{% endif %}>Movie</option>
                <option value="Theater" {% if eventType == 'Theater' %}selected{% endif %}>Theater</option>
                <option value="Food" {% if eventType == 'Food' %}selected{% endif %}>Food</option>
                <option value="Art" {% if eventType == 'Art' %}selected{% endif %}>Art</option>
                <option value="Other" {% if eventType == 'Other' %}selected{% endif %}>Other</option>
            </select>
        </form>
    </div>

    
   
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
        {% for event in events %}
        <div class="mx-auto col mb-4" >
            <div class="cardColor card mx-auto" style="width: 18rem;">
                <img src='{{event.image}}' class="card-img-top" alt="{{ event.name }}">
                <div class="card-body">
                <h5 class="card-title">{{ event.name }}</h5>
                <p class="card-text">{{ event.eventDateTime ? event.eventDateTime|date('Y-m-d H:i:s') : '' }}</p>
                <p class="card-text">{{ event.adress }}</p>
                <a class="btn btn-success" href="{{ path('app_events_show', {'id': event.id}) }}">Details</a>
                <a class="btn btn-danger" href="{{ path('app_events_edit', {'id': event.id}) }}">Update</a>
                </div>
            </div>
        </div>
        {% else %}
        <h1> You don't have an record</h1>
      {% endfor %}
    </div>
    <h4 class="text-center">
    <a class="btn btn-outline-dark indexbtn " href="{{ path('app_events_new') }}">Create a new Event</a>
</h4>
    {% endblock %}

        
            
    

templates/events/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Events{% endblock %}

{% block body %}
    <h1 class="text-center">Create new Events</h1>
 
    <div class="container">
        {{ include('events/_form.html.twig') }}
        <br>
        <div class="text-center">
            <a class="btn btn-dark fs-3" href="{{ path('app_events_index') }}">Back to Events</a>
        </div>

    </div>


{% endblock %}

templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('details.css') }}">
{% endblock %}

{% block title %}Events{% endblock %}

{% block body %}
    <h1 class="text-center">{{ event.name }}</h1>

    {# <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>EventDateTime</th>
                <td>{{ event.eventDateTime ? event.eventDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ event.image }}</td>
            </tr>
            <tr>
                <th>Capacity</th>
                <td>{{ event.capacity }}</td>
            </tr>
            <tr>
                <th>Contact_email</th>
                <td>{{ event.contactEmail }}</td>
            </tr>
            <tr>
                <th>Contact_phone_number</th>
                <td>{{ event.contactPhoneNumber }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ event.adress }}</td>
            </tr>
            <tr>
                <th>Event_URL</th>
                <td>{{ event.eventURL }}</td>
            </tr>
            <tr>
                <th>EventType</th>
                <td>{{ event.eventType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_events_index') }}">back to list</a>

    <a href="{{ path('app_events_edit', {'id': event.id}) }}">edit</a>

    {{ include('events/_delete_form.html.twig') }} #}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="project-info-box mt-0 ">
                <h5>EVENT DETAILS</h5>
                <p class="mb-0">{{ event.description }}</p>
            </div><!-- / project-info-box -->

            <div class="project-info-box">
                <p><b>Adress:</b> {{ event.adress }}</p>
                <p><b>Date:</b> {{ event.eventDateTime ? event.eventDateTime|date('Y-m-d H:i:s') : '' }}</p>
                <p><b>Capacity:</b> {{ event.capacity }}</p>
                <p><b>Phone Number:</b> {{ event.contactPhoneNumber }}</p>
                <p class="mb-0"><b>Type:</b>{{ event.eventType }}</p>
            </div><!-- / project-info-box -->

            <div class="project-info-box mt-0 mb-0">
                <p class="mb-0">
                    <span class="fw-bold mr-10 va-middle hide-mobile">Buy now: 
                        <a href="https://www.viennacitycard.at/en/">https://www.viennacitycard.at/en/</a>
                  
            </div>
        </div>

        <div class="col-md-7">
            <img src="{{ event.image }}" alt="project-image" class="rounded">
            <div class="project-info-box">
                <p><b>Email:</b> <a href="">{{ event.contactEmail }}</a></p>
                <p><b>URL:</b> <a href="">{{ event.eventURL }}</a></p>
            </div>
        </div>
    </div>
</div>
<br>
<div class="text-center">
    <a class="btn btn-dark fs-3" href="{{ path('app_events_index') }}">Back to Events</a>
    <a class="btn btn-dark fs-3" href="{{ path('app_events_edit', {'id': event.id}) }}">Update event</a>
</div>
<div class="text-center">
    {{ include('events/_delete_form.html.twig') }}
</div>
{% endblock %}